FROM golang:1.22 AS build

WORKDIR /usr/src

COPY go.mod go.sum ./
RUN go mod download && go mod verify

ADD . .

RUN ["go", "build", "-o", "api", "app/service/main.go"]


FROM debian:12

WORKDIR /

COPY --from=build /usr/src/api /bin/api

CMD [ "/bin/api" ]